# Generated by Django 5.2.5 on 2025-08-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gishe', '0002_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
