# Generated by Django 5.2.5 on 2025-09-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gishe', '0003_rename_first_name_customer_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name', 'email'], name='gishe_custo_name_4d8594_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='gishe_customers',
        ),
    ]
