# Generated by Django 5.2.5 on 2025-09-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gishe', '0004_customer_gishe_custo_name_4d8594_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='gishe_custo_name_4d8594_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
